import path from "node:path";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";

const host = process.env.TAURI_DEV_HOST;

// https://vite.dev/config/
export default defineConfig(async () => ({
  plugins: [
    tanstackRouter({
      target: "react",
      routesDirectory: "./src/app/routes",
      generatedRouteTree: "./src/app/routeTree.gen.ts",
      virtualRouteConfig: "./src/app/routes.ts",
      quoteStyle: "double",
      semicolons: true,
      routeTreeFileHeader: [
        "// biome-ignore-all lint: generated by TanStack Router",
      ],
    }),
    react(),
  ],
  resolve: {
    alias: {
      "@": "/src",
      "@features-manifest": path.resolve(__dirname, "../preview-features.json"),
      "@model-capabilities-manifest": path.resolve(
        __dirname,
        "../scripts/model-capabilities.json",
      ),
    },
  },

  // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
  //
  // 1. prevent Vite from obscuring rust errors
  clearScreen: false,
  // 2. tauri expects a fixed port, fail if that port is not available
  server: {
    port: parseInt(process.env.VITE_PORT || "1420", 10),
    strictPort: true,
    host: host || false,
    hmr: host
      ? {
          protocol: "ws",
          host,
          port: parseInt(process.env.VITE_HMR_PORT || "1421", 10),
        }
      : undefined,
    watch: {
      // 3. tell Vite to ignore watching `src-tauri`
      //
      // Divergencia Pimia: y la salida de los e2e. Playwright reescribe
      // `playwright-report/` y `test-results/` en cada pasada, Vite lo veía como
      // un cambio del proyecto y **recargaba la página entera de la app de
      // escritorio**. Una recarga a media invocación deja huérfano el callback
      // del comando Tauri en vuelo («Couldn't find callback id …») y la UI se
      // queda esperando para siempre — así se colgó el primer login de Pimia
      // real, con la suite corriendo en paralelo.
      ignored: [
        "**/src-tauri/**",
        "**/playwright-report/**",
        "**/test-results/**",
        "**/dist/**",
      ],
    },
  },
}));
